### PR TITLE
More tables

### PR DESCRIPTION
**Pull request by timw-rivos**
### Summary of the PR

This PR adds support for seven more tables, several of which are created manually inside rust-cloud-hypervisor. Some of that code could be removed there and reused from this library.

### Requirements

Before submitting your PR, please make sure you addressed the following
requirements:

- [x] All commits in this PR are signed (with `git commit -s`), and the commit
  message has max 60 characters for the summary and max 75 characters for each
  description line.
- [x] All added/changed functionality has a corresponding unit/integration
  test.

### CODE REVIEW

**Review by sboeuf — DISMISSED** [review]
LGTM

**Review by rbradford — APPROVED** [review]

**Comment by rbradford** [comment]
Hi @timw-rivos this PR needs a rebase before it can be merged.

**Comment by timw-rivos** [comment]
I think the rebase was successful, but now all of the quality checks are failing and I'm not quite sure why because I cannot reproduce those failures locally :( For me, the each commit looks clean for each of cargo check, cargo clippy, cargo fmt, and cargo test.

**Comment by sboeuf** [comment]
> I think the rebase was successful, but now all of the quality checks are failing and I'm not quite sure why because I cannot reproduce those failures locally :( For me, the each commit looks clean for each of cargo check, cargo clippy, cargo fmt, and cargo test.

It looks like the rebase was successful indeed, given you still have your 12 commits and that now Github doesn't complain about your branch being out of sync.

But it seems like you have a bunch of issues trying to move references out of `self` in `cedt.rs`. You should follow what the Rust compiler suggests, that is implement the Copy trait for these types. And I suspect you might have similar issues with other files, so please make sure to run `cargo clippy --all` locally to find out about all the potential errors.

**Review by sboeuf — APPROVED** [review]

**Review by rbradford — APPROVED** [review]

**Pull request merged**
